### ISSUE TITLE
Suggestion: rename to "000/001_ClickThroughFix"

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [linuxgurugamer/ClickThroughBlocker#1]
Hi, I've found that Antenna Helper 1.0.4 doesn't work for me, whereas 1.0.3 does.  My suspicion is that the issue is that AntennaHelper gets loaded before ClickThroughBlocker.  @li0n-0 could change the name to "DAntennaHelper" or something, but I think it would be better if you moved CTB up to the 000/001 part of the alphabet -- this might cause short-term trouble for other mods that use it, but it would future-proof it against other mods in A-C land from having trouble.

**Comment by linuxgurugamer** [comment]
It's a good suggestion.  I don't need to change the dll, just the directory name.

Thanks, I'll get to it this evening

**Comment by Kerbas-ad-astra** [comment]
Actually, I just tried that myself and Antenna Helper 1.0.4 still doesn't work, so there must be something else going on.  (Probably still a good idea to rename it though.)

**Comment by linuxgurugamer** [comment]
Interesting, but yes, I am going to rename it
