### ISSUE TITLE
Game Crashes On Splash Screen

### ISSUE THREAD

**Issue by RivenWasTaken** [linuxgurugamer/ClickThroughBlocker#10]
I open the game one day and it won't open.  If this mod is in the gamedata folder, the game crashes on splash.  Any other mods and it starts fine.

Log https://pastebin.com/9Xk4G1iG

**Comment by linuxgurugamer** [comment]
Is that the full log?  Because it looks very small.
What do you mean about being in the GameData folder, that's where it belongs.  And if it was crashing KSP, then there are 200 other mods which use it, so it sounds like an install issue.

**Comment by RivenWasTaken** [comment]
That's the full log.  What I meant was if it's installed it crashes the game.  I also tried redownloading and reinstalling.  
If I have this mod with the other mods, the game crashes.  If I have only the other mods, it does not crash.  If I have only this mod and no others, it crashes.

**Comment by linuxgurugamer** [comment]
Oh.  You probably have MiniAVC.dll in that folder, delete it.
Would be a good idea to install ZeroMiniAVC to make sure you don't have any MiniAVC.dll files, it's seriously broken in 1.8

**Comment by linuxgurugamer** [comment]
Please let me know if the message above fixes it.  I'm closing this for now, feel free to reopen it if the problem still exists
