### ISSUE TITLE
TypeLoadException Spam in Log/Console leads to unplayable stuttering.

### ISSUE THREAD

**Issue by moreorlessgit** [linuxgurugamer/ClickThroughBlocker#11]
This just keeps getting repeated in the log over and over again. I affixed my modlist and can provide the log if needed. On version 1.6.1 installed through CKAN.

TypeLoadException: Could not load type 'ClickThroughFix.ClickThruBlocker' from assembly 'ClickThroughBlocker, Version=0.1.9.5, Culture=neutral, PublicKeyToken=null'.

![26caa3ea17746b61e31cd83010c23edb](https://user-images.githubusercontent.com/10689972/72225634-a67e2a80-3555-11ea-8c0c-e18099f7228e.png)

**Comment by moreorlessgit** [comment]
Heres the log. It was 100MB... Had to zip it.

[KSPLog.zip](https://github.com/linuxgurugamer/ClickThroughBlocker/files/4051453/KSPLog.zip)

**Comment by linuxgurugamer** [comment]
I don't know why CKAN installed that version, you installed the version which was done for 1.8.  Did you enable compatibility for 1.8 in CKAN??

You want to install this version:  
https://github.com/linuxgurugamer/ClickThroughBlocker/releases/tag/0.1.7.2
