### ISSUE TITLE
The dialog to select mouse or click based selection needs click-thru protection itself

### ISSUE THREAD

**Issue by SteveBenz** [linuxgurugamer/ClickThroughBlocker#14]
I run with QuickStart, and found that when I clicked on any of the controls, the click went through to the KSP Escape-button dialog which was behind it.

**Comment by linuxgurugamer** [comment]
This isn't a bug, it's a limitation of the game.  KSP doesn't use the CTB, so CTB can't protect against clicks falling through to the stock controls
