### ISSUE TITLE
No contracts appearing in career mode Mission Control

### ISSUE THREAD

**Issue by apete343** [linuxgurugamer/ClickThroughBlocker#16]
I recently updated all of my mods and noticed that when I start a new game, or resume a saved game, and go to Mission control, there are no contracts in any of the 3 tabs. From my crude/layman debugging, it seems like the issue was related to this mod.

Steps I took:
- I redownloaded KSP (`1.10.1.2932`; on macOS `10.14.4`/Steam) and removed all mods; the issue was gone.
- I added mods back one at a time (individually, without other mods) to test when the issue came back
- The issue came back when I added the latest version of `ClickThroughBlocker`
- I iterated backward through versions of `ClickThroughBlocker` and observed that the latest "good" version (that didn't have this issue for me) is `0.1.10.1`

Please let me know if there is anything else I can provide that would be helpful, if you think this could be a real issue. Thanks!

**Comment by linuxgurugamer** [comment]
Log file would be useful.
You are the only person to have this problem.  
That's the last version before the new FocusFollowsClick mode was added.
I can't imagine what it can do, this has nothing to do with the contracts.

**Comment by apete343** [comment]
Cool, well if it's just me then nothing to worry about. I'll see if I can get a log though

**Comment by apete343** [comment]
Just re-installed the latest mod to get a log file. I notice this in the log:

```
[EXC 14:15:52.080] FileNotFoundException: Could not load file or assembly 'ToolbarControl, Version=0.1.8.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

If I install the `ToolbarControl` mod and restart, the issue is resolved.

I guess the `ToolbarControl` is a dependency; I haven't had much luck with KSP dep managers though so I had just downloaded `ClickThroughBlocker` straight from Github and didn't notice mention of it there.

Anyway missing dependency explains it, but possibly worth noting that it manifested as a "no contracts" issue in-game.

[Here is the log file](https://pastebin.com/xtiyF1wH)

Thanks

**Comment by linuxgurugamer** [comment]
Doesn't matter, the initial error was in the log file.
I don't need it now, glad you figured it out.
This is why I recommend CKAN for all my mods.
