### ISSUE TITLE
No matter what I set up in game parameters prior career start - on first scene load CTB always asks

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/ClickThroughBlocker#17]
In the "game settings" I already can choose which method CTB shall use.
I can even tell it's default for all new games.
But CTB still asks on new careers on first scene load (SPC) which method to use.

**Comment by linuxgurugamer** [comment]
There is toggle on the settings page saying: "Show Popup at next start", if  you don't want it to show next time, you just deselect this toggle
