### ISSUE TITLE
Not removing input locks on window close

### ISSUE THREAD

**Issue by siimav** [linuxgurugamer/ClickThroughBlocker#18]
A good illustration of the problem is the CTB startup window itself.
Video clip: https://drive.google.com/file/d/1_MUQxCOpd5rBbyWD0bgVEo7k_p0HE1MN/view?usp=sharing

**Comment by linuxgurugamer** [comment]
Thanks, I am aware of it and will get it fixed in the next day or so.
One thing about is is that it only happens in the FocusFollowsMouse mode, which is why I never noticed it, since I always use FocusFollowsClick

**Comment by linuxgurugamer** [comment]
fixed in release

**Comment by siimav** [comment]
I see that you've manually cleared input locks on the accept button but not for cancel.
Actually this issue isn't limited to only CTB's own startup dialog. I only brought that up as a quick and dirty example. Any mod that has a button for closing the window will retain CTB input locks after using said button. You can use KCT's *Settings* window or *New pad* dialogs as an example of that.

**Comment by linuxgurugamer** [comment]
Oh, yuck.  I'll get that fixed. 

I'll look into the rest of it as well later this week.

**Comment by linuxgurugamer** [comment]
Will be fixed in next release
