### ISSUE TITLE
0.1.6.4 is not satisfying prerequisite

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [linuxgurugamer/ClickThroughBlocker#2]
Version 0.1.6.4 fails to satisfy the prerequisite for several mods, causing them to stop working.  With FuseBox, this means that all parts completely fail to load, which means all ships in flight get eaten.  (Don't worry about my Kerbals, I'm still working with test installs so nothing was "lost".)

I think removing this line was the cause of the issue: https://github.com/linuxgurugamer/ClickThroughBlocker/commit/81c625f6f266c80fc9db4d68dd5180a41e7482ba#diff-03b0b2211a261e86d9954e82a8302cc6L38

**Comment by linuxgurugamer** [comment]
which doesn' tmake sense, since it was merely requiring itself as a dependency.
I've removed the release, will do some testing later on

**Comment by linuxgurugamer** [comment]
I tried adding that line back, and it was still failing in my testing :-(

Need to figure this out before I can release the update again

**Comment by linuxgurugamer** [comment]
Actually, it is working, there was another issue, unrelated to this.
Thanks for pointing this out, I'm going to post a beta before releasing this

**Comment by linuxgurugamer** [comment]
https://jenkins.spacetux.net/job/A-F/job/ClickThroughBlocker/lastSuccessfulBuild/artifact/000_ClickThroughBlocker-0.1.6.5.zip

**Comment by Kerbas-ad-astra** [comment]
That build works for me.

**Comment by linuxgurugamer** [comment]
thanks, just released it
