### ISSUE TITLE
Clearing input locks allows control of uncontrolled ships!

### ISSUE THREAD

**Issue by Goufalite** [linuxgurugamer/ClickThroughBlocker#21]
Quick video to show the problem : https://www.youtube.com/watch?v=wGUjs1P-4oU

Steps :
* Clean install of KSP 1.11.2 and it's addons MH and BG
* Install Toolbar Continued from CKAN which will install CTB as a dependency
* Create a new career save
* Alt+F12 all technologies, and facilities

Test 1:
* Build a ship not supposed to be controlled (no kerbal, no probe)
Expected : the ship is not controllable
Obtained : **the ship IS controllable**, can rotate if it has a reaction wheel and electricity, can turn if it's a rover wheel

Test 2 : 
* launch a mk1 pod with a kerbal
* EVA the kerbal and switch to the pod
Expected and obtained : the pod is uncontrollable
* Click on "Clear input locks"
Expected : the pod is uncontrollable
Obtained : **the pod is controllable** and SAS can be activated although it doesn't have a SAS module
* Switch to the kerbal and back to the pod
Expected and obtained : the pod is uncontrollable
* Click on "Clear input locks"
Expected : the pod is uncontrollable
Obtained : **the pod is controllable** and SAS can be activated although it doesn't have a SAS module
* Switch to the kerbal and back to the pod

After removing all mods, the problem doesn't appear

The impact is that we can control ships without paying attention which could lead to happily resolved situations. Also CTB and Toolbar controller and a dependency of a LOT of mods, especially non gameplay mods such as station keeping.

Ready to give more info if wanted ;)

**Comment by fipachu** [comment]
Can confirm, is annoying.

**Comment by linuxgurugamer** [comment]
Have you tried clearing the input locks manually, without using CTB?  and if so, does it happen then?

**Comment by Goufalite** [comment]
Does manually doing this is Debug Toolbar => Command lock? (I'm playing French so wording might not be the same). Here's what happens :

Test 1 (wheel without control)
**Upon scene load no control** (expected), but when manually unlocking, SAS/control is possible. Which is different than above (with CTB the craft is controllable directly on scene load).

Test 2 (command pod)
Same as above (need to click on unlock to unlock the controls)

So yeah, Clearing input locks works as "intended"/stock, but the control on scene load is what's different

**Comment by linuxgurugamer** [comment]
Ok, I've confirmed the problem.  This is the result of an old fix for a bug in KSP which has been fixed.

Please try this beta, this only contains the dll
[ClickThroughBlockerBeta.zip](https://github.com/linuxgurugamer/ClickThroughBlocker/files/6601885/ClickThroughBlockerBeta.zip)

Your instructions were very clear, thank you for doing the extra effort.

Assuming it works for you, could you also try it on a game which is fairly advanced?  ie:  many flying vessels, big ship, lots of mods, etc.  This is a timing issue, I need to be sure it works as intended.  Specifically, I'd be concerned about vessels which SHOULD have control but dont

**Comment by Goufalite** [comment]
On it!

Works well on the initial vanilla testbench. I'm including it in my 40-mods career mode run.

**Comment by linuxgurugamer** [comment]
Released, thank you
