### ISSUE TITLE
CTB conflicts with mechjeb even though they don't interact

### ISSUE THREAD

**Issue by KerbalHub** [linuxgurugamer/ClickThroughBlocker#24]
How to replicate:
1. have the latest version of MechJeb and CTB installed
2. go to the VAB
3. add a part with MJ
4. click the settings window
5. THE SETTINGS WINDOW IS GLITCHED!

**Comment by linuxgurugamer** [comment]
Log file

**Comment by KerbalHub** [comment]
[KSP.log](https://github.com/linuxgurugamer/ClickThroughBlocker/files/9032148/KSP.log)
Here you go.

**Comment by linuxgurugamer** [comment]
I prefer the Player.log

**Comment by KerbalHub** [comment]
[Player.log](https://github.com/linuxgurugamer/ClickThroughBlocker/files/9032157/Player.log)
You mean this file?

**Comment by linuxgurugamer** [comment]
Yes, but both files are substantially truncated.

I would also suggest updating to 1.12.3

I'm also going to ask that you continue this on the forum; every time someone has complained about this, turned out to be something else.  The complete logs will help figure that out
