### ISSUE TITLE
0.1.6.6: log spamming in VAB

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/ClickThroughBlocker#3]
```
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[Part].get_Item (Int32 index) [0x00000] in <filename unknown>:0 
  at ClickThroughFix.CBTMonitor.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```
Log and all that stuff:
https://www.dropbox.com/s/radbpet46u8wt4d/2018-07-21_1%20KSP.log.7z?dl=1

**Comment by Gordon-Dry** [comment]
Somehow this issue seems to be the reason for not being able to extend antennas in VAB.
At least with the Bluedog DB vanguard antenna (the one with the built-in solar panel).
RemoteTech is installed.

**Comment by linuxgurugamer** [comment]
Silly error, will be fixed asap
Thanks

**Comment by linuxgurugamer** [comment]
Is that one the M17 Solar Antenna?

**Comment by Gordon-Dry** [comment]
bluedog_solarAntenna

btw I have to recheck now when I'm back into the game ...
