### ISSUE TITLE
Sometimes focus gets changed to main controls in VAB

### ISSUE THREAD

**Issue by se5a** [linuxgurugamer/ClickThroughBlocker#4]
This is hard to reproduce reliably though it happens frequently enough to be frustrating.

Create a vehicle, mousewheel should scroll in and out in the spaceplane designer or up and down in the VAB. 

After right clicking and moving the camera around, sometimes using the mousewheel will flick between menu items such as the Build, Actions, Crew and Switch Editor buttons.
Right Clicking anywhere in the editor normally refocuses it properly. 

I've had something similar happen while flying too, ie space not deploying the stage etc, which I suspect is related.

It's possibly related to interaction with other mod windows, or maybe some sort of race condition with them. I was able to reproduce it more often if the cursor passed over these windows while rclick camera panning, but not always, and cursor location on mouseUp didn't *seem* to make any difference. 

Kerbal Alarm clock, Kerbal Engineer Redux, were the two windows I had open in the VAB while this was happening. problem appears to go away completely when ClickThroughBlocker is removed, and re-appears when re-added. 

KSP 1.4.4 Linux. 
Clickthrough Blocker 0.1.6.7 installed via CKAN

**Comment by linuxgurugamer** [comment]
As you say, it is difficult.  This mod doesn't do anything with the mouse wheel, 
KER, KAC don't even use this.
A video would be helpful.

**Comment by linuxgurugamer** [comment]
Also, a question:  
I gather that you are using the right-click to pan around.  Do you release the right-click before trying the mousewheel?

**Comment by se5a** [comment]
yeah right click drag for camera control, and yes I was releasing rightclick before mousewheel.
the mousewheel has little to do with it really, it was just the best way to describe what looks to be happening - ie the focus is getting switched to the wrong place. 

It seemed to be more prevalent with larger designs which is why I was thinking it was maybe a race condition of some sort. 
I'll try get a video

**Comment by se5a** [comment]
ah. 
there appears to be some sort of ghost window in the bottom right of KSP which it's picking up it looks like. if the cursor is down in that area it'll get caught.

**Comment by se5a** [comment]
It seems to happen when the cursor is directly below Kerbal Alarm Clock window (ie + y axis) so I guess the problem could be with KAC.

**Comment by linuxgurugamer** [comment]
Closing for now, until and unless you can be a bit more specific.  For now, assuming it's with KAC

**Comment by Gordon-Dry** [comment]
KAC again... so many issues...

**Comment by linuxgurugamer** [comment]
And unfortunately, the author is still around, so I won't even consider touching it
