### ISSUE TITLE
Inability to Click on 1.7

### ISSUE THREAD

**Issue by diveyez** [linuxgurugamer/ClickThroughBlocker#5]
Since the update, I cannot click anything with this mod loaded

**Comment by linuxgurugamer** [comment]
You have to be more specific than that.  
You also need to provide a log file.
So far, in my admittedly minimal testing, I haven't had any problem, and if there was a problem with the mod the way you described, I'd be getting lots of messages on the forums.  So far it's been quiet

**Comment by linuxgurugamer** [comment]
I will be closing this soon if no response

**Comment by linuxgurugamer** [comment]
Reopen if you have more information
